name: Publish Python Mpesa SDK distribution to TestPyPI

on:
  push:
    branches: [ develop ]

jobs:
  build-n-publish:
    name: Build and publish Python Mpesa SDK distribution to TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: python -m pip install --upgrade pip
    - run: python -m pip install pep517 --user
    - run: python -m pep517.build --source --binary --out-dir dist/ .
    - run: pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install dependencies & build
      run: |
        python -m pip install --upgrade pip
        python -m pip install pep517 --user
        python -m pep517.build --source --binary --out-dir dist/ .
        pip install -r requirements.txt
#    - name: Test with pytest
#      run: |
#        pip install pytest
#        pytest
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}